export const RECEIVE_CATEGORIES = "RECEIVE_CATEGORIES";
export const FAILED_RECIEVE_CATEGORIES = "FAILED_RECIEVE_CATEGORIES";

export const RECEIVE_PRODUCTS = "RECEIVE_PRODUCTS";
export const FAILED_RECIEVE_PRODUCTS = "FAILED_RECIEVE_PRODUCTS";
